export const SCOPE_TYPE = {
    BRAND_FILM: 'BRAND_FILM',
    BRAND_STORY: 'BRAND_STORY',
    BRAND_IDENTITY: 'BRAND_IDENTITY',
    GOODS: 'GOODS',
    GRAPHIC_MOTIF: 'GRAPHIC_MOTIF',
    MARKETING: 'MARKETING',
    MANAGING: 'MANAGING',
    NAMING: 'NAMING',
    PACKAGE: 'PACKAGE',
    PHILOSOPHY: 'PHILOSOPHY',
    WORKSHOP: 'WORKSHOP',
} as const
export type ScopeType = (typeof SCOPE_TYPE)[keyof typeof SCOPE_TYPE]
